apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: snake-gameserver
spec:
  replicas: 1
  template:
    spec:
      ports:
      - name: default
        portPolicy: Static
        protocol: TCP
        hostPort: 443
        containerPort: 8082
      health:
        disabled: false
        initialDelaySeconds: 5
        failureThreshold: 10
      sdkServer:
        logLevel: Debug
      template:
        spec:
          containers:
          - name: snake-gameserver
            image: gcr.io/yoan-dev-313023/snake-gameserver:1.0.0
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: "64Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "20m"
