---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake
  namespace: snake
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snake
  template:
    metadata:
      labels:
        app: snake
    spec:
      containers:
      - name: snake-server
        image: snake-server:1.0
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service 
metadata:
  name: snake
  namespace: snake
spec:
  type: NodePort 
  selector:
    app: snake
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080