---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake
  namespace: snake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake
  template:
    metadata:
      labels:
        app: snake
    spec:
      containers:
      - name: snake-server
        image: snake-server:1.0.1
        imagePullPolicy: IfNotPresent
      - name: snake-frontend
        image: snake-frontend:1.0.6
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service 
metadata:
  name: snake
  namespace: snake
spec:
  type: NodePort 
  selector:
    app: snake
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sanake
  namespace: snake
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: snake-game.myoan.dev
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: snake
                port:
                  number: 80