---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-frontend
  template:
    metadata:
      labels:
        app: snake-frontend
    spec:
      containers:
      - name: snake-frontend
        image: snake-frontend:1.0.6
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-backend
  template:
    metadata:
      labels:
        app: snake-backend
    spec:
      serviceAccountName: agones-sdk
      containers:
      - name: snake-backend
        image: snake-backend:1.0.0
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service 
metadata:
  name: snake-ui
spec:
  type: NodePort 
  selector:
    app: snake-frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: snake-api
spec:
  type: NodePort 
  selector:
    app: snake-backend
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: snake-game.myoan.dev
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: snake-ui
                port:
                  number: 80
    - host: api.snake-game.myoan.dev
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: snake-api
                port:
                  number: 8080