# https://taskfile.dev

version: '3'

vars:
  BINARY_DIR: bin
  LOG_DIR: log

tasks:
  build:
    cmds:
      - task: build_client
      - task: build_server
  build_echo:
    cmds:
      - task: build_echo_client
      - task: build_echo_server
  build_client:
    dir: client
    cmds:
      - go build
      - mv client ../{{.BINARY_DIR}}
    silent: true
  build_server:
    dir: server
    cmds:
      - go build
      - mv server ../{{.BINARY_DIR}}
    silent: true
  clean:
    cmds:
      - rm -rf {{.BINARY_DIR}}/*
      - rm -rf {{.LOG_DIR}}/*
  build_echo_client:
    dir: echoc
    cmds:
      - go build
      - mv echoc ../{{.BINARY_DIR}}
  build_echo_server:
    dir: echo
    cmds:
      - go build
      - mv echo ../{{.BINARY_DIR}}
