# https://taskfile.dev

version: '3'

vars:
  BINARY_DIR: bin
  LOG_DIR: log

tasks:
  build:
    cmds:
      - task: build_client
      - task: build_server
  build_client:
    dir: client
    cmds:
      - go build
      - mv client ../{{.BINARY_DIR}}
    silent: true
  build_server:
    dir: server
    cmds:
      - go build
      - mv server ../{{.BINARY_DIR}}
    silent: true
  clean:
    cmds:
      - rm -rf {{.BINARY_DIR}}/*
      - rm -rf {{.LOG_DIR}}/*
  docker:
    build:
      cmds:
        - task: docker_backend
        - task: docker_frontend
        - task: docker_game
  docker_nginx:
    cmds:
      - docker build -f docker/Dockerfile.nginx -t gcr.io/yoan-dev-313023/snake-nginx:1.0.0 .
  docker_backend:
    cmds:
      - docker build -f docker/Dockerfile.backend -t gcr.io/yoan-dev-313023/snake-backend:1.0.1 .
  docker_frontend:
    cmds:
      - docker build -f docker/Dockerfile.frontend -t gcr.io/yoan-dev-313023/snake-frontend:1.0.21 .
  docker_game:
    cmds:
      - docker build -f docker/Dockerfile.gameserver -t gcr.io/yoan-dev-313023/snake-gameserver:1.0.0 .
  k8s_server:
    cmds:
      - kubectl apply -f ./server.yaml
  k8s_game:
    cmds:
      - kubectl apply -f ./gameserver.yaml
