# https://taskfile.dev

version: '3'

vars:
  BINARY_DIR: bin
  LOG_DIR: log

tasks:
  build:
    cmds:
      - task: build_client
      - task: build_server
  build_client:
    dir: client
    cmds:
      - go build
      - mv client ../{{.BINARY_DIR}}
    silent: true
  build_server:
    dir: server
    cmds:
      - go build
      - mv server ../{{.BINARY_DIR}}
    silent: true
  clean:
    cmds:
      - rm -rf {{.BINARY_DIR}}/*
      - rm -rf {{.LOG_DIR}}/*
  docker:
    build:
      cmds:
        - task: docker_backend
        - task: docker_frontend
        - task: docker_gameserver
  docker_backend:
    dir: backend
    cmds:
      - docker build -t snake-backend:latest .
  docker_frontend:
    dir: frontend
    cmds:
      - docker build -t snake-front:latest .
  docker_gameserver:
    dir: gameserver
    cmds:
      - docker build -t snake-gameserver:latest .
  k8s_server:
    - kubectl apply -f server.yml
  k8s_game:
    - kubectl apply -f gameserver.yml